spring.application.name=product-service-spring-boot

spring.data.mongodb.uri=mongodb://admin:password@localhost:27017/product-service?authSource=admin

server.address=0.0.0.0

# OpenAPI Configuration
# Disable SpringDoc generation
springdoc.api-docs.enabled=false
# Basic UI path
springdoc.swagger-ui.path=/swagger-ui.html

springdoc.swagger-ui.url=/openapi.yaml


# Logging for debugging
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=TRACE
logging.level.org.springframework.web.cors=TRACE
logging.level.org.springframework.cloud.gateway=TRACE
logging.level.org.springframework.http=DEBUG
logging.level.io.micrometer.tracing=DEBUG

# Enable Spring Boot Observability (Spring Boot 3+)
management.tracing.enabled=true
management.observations.enabled=true

# Disable metrics and logs if chỉ muốn trace
management.otlp.metrics.export.enabled=false
management.otlp.tracing.endpoint=http://localhost:4318/v1/traces
otel.traces.exporter=logging
otel.exporter.otlp.protocol=http/protobuf

management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.observations.key-values.application=product-service-spring-boot
management.tracing.sampling.probability=1.0
management.endpoints.web.exposure.include=*

# Actuator Endpoints
management.health.circuitbreakers.enabled=true
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# Thay đổi base path của actuator
management.endpoints.web.base-path=/
management.endpoints.web.path-mapping.health=health

# Enable health endpoint and specific health groups
management.endpoint.health.probes.enabled=true
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true
