openapi: 3.0.3
info:
  title: Product Service API
  description: This is the REST API for Product Service
  version: v0.0.1
  license:
    name: Apache 2.0
externalDocs:
  description: You can refer to the Product Service Wiki Documentation
  url: https://product-service-dummy-url.com/docs
servers:
  - url: http://localhost:8080
    description: Local development server
paths:
  /api/product:
    get:
      summary: Get all products
      description: Retrieve a list of all available products
      operationId: getAllProducts
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProductResponse'
    post:
      summary: Create a new product
      description: Add a new product to the system
      operationId: createProduct
      requestBody:
        description: Product information to be added
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductRequest'
      responses:
        '201':
          description: Product created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductResponse'
  /api/product/debug:
    get:
      summary: Debug endpoint
      description: Checks if ProductService bean exists
      operationId: debug
      responses:
        '200':
          description: Successful operation
          content:
            text/plain:
              schema:
                type: string
components:
  schemas:
    ProductRequest:
      type: object
      required:
        - name
        - description
        - skuCode
        - price
      properties:
        name:
          type: string
          example: "iPhone 13"
        description:
          type: string
          example: "Apple iPhone 13 with 128GB storage"
        skuCode:
          type: string
          example: "IPHONE13-128"
        price:
          type: number
          format: decimal
          example: 999.99
    ProductResponse:
      type: object
      properties:
        id:
          type: string
          example: "60f4a5e9b3c24a1a1c9d2e4f"
        name:
          type: string
          example: "iPhone 13"
        description:
          type: string
          example: "Apple iPhone 13 with 128GB storage"
        skuCode:
          type: string
          example: "IPHONE13-128"
        price:
          type: number
          format: decimal
          example: 999.99 