networks:
  product-service-network:
    driver: bridge
  microservices-spring-network:
    external: true

services:
  mongo:
    image: mongo:8.0.6
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=product-service
    volumes:
      - ./data:/data/db
    networks:
      - product-service-network
      - microservices-spring-network
