helm-template:
  name: "product-service" 

  image:
    repository: product-service
    tag: 1
    pullPolicy: IfNotPresent
    port: 8080

  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 80

  service:
    enabled: true
    type: ClusterIP
    port: 8080

  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi

  ingress:
    enabled: false

  configmap:
    enabled: false
  
  service-account:
    enabled: true
    name: product-service
    annotations:
      eks.amazonaws.com/role-arn: xxx
    automountServiceAccountToken: true

  externalSecrets:
    enabled: true
    key: product-service-secret

